### ISSUE TITLE
Create Sign Up Form For the Code For Greenville Slack

### ISSUE THREAD

**Issue by allella** [codeforgreenville/codeforgreenville.github.io#13]

**Comment by allella** [comment]
Hey @jeremywight it would be great if you could create a form for sign up and I'll add it to the website.

**Comment by jeremywight** [comment]
Created a Google Form which a user can submit an email to which sends an invite to the codeforgreenville.slack.com group and sends a message to the #brigade-organizers channel.

**Comment by jeremywight** [comment]
https://forms.gle/Ys7B9wnvNR7m3avWA
