### ISSUE TITLE
Write Brigade Meeting Recap Posts

### ISSUE THREAD

**Issue by wryenmeek** [codeforgreenville/codeforgreenville.github.io#2]
I need someone to volunteer to write up post meeting blog posts for the site.

**Comment by allella** [comment]
FYI, nobody subscribes to these things.

**Comment by allella** [comment]
How is the blog edited? Does Git have a WYSIWYG of some sorts? Or do you have to download something like Jekyll?

**Comment by allella** [comment]
I guess this is the way to do it
https://help.github.com/articles/creating-pages-with-the-automatic-generator

**Comment by wryenmeek** [comment]
Directions should be on the site repo readme.md file

Short version
Its an octopress site. *A jekyll framework.) Posts are written in markdown
and committed to the source branch of the repo. Then you generate the site
from the new site and comit it to the master branch so github pages can
display the html/css/javascript files.

**Comment by allella** [comment]
Closing as we're going to keep the website simple to start.

See
https://github.com/codeforgreenville/codeforgreenville.github.io/issues/4
