### ISSUE TITLE
Newer, Simpler Website

### ISSUE THREAD

**Issue by allella** [codeforgreenville/codeforgreenville.github.io#4]
The old/ existing site is using Octopress. See https://github.com/codeforgreenville/codeforgreenville.github.io/issues/2#issuecomment-56659077 for old notes.

I (@allella) stripped all the out of date stuff out of the raw HTML (not using the proper Octopress methods) about two months ago in order to get things looking more current.  It's bare as can be, but not out of date.  We could use a new, simple, responsive template and basic content like
- Links to the active projects  (Trolley Tracker and data.openupstate.org). Might be nice to also link to the Github projects as a secondary link
- Link to the meetup.com page and/or a widget to show upcoming events

The codeforegreenville.org domain is paid for by OpenWorks and Jim (@allella) has access to the registrar and DNS.  The hosting is currently using GitHub Pages (free). If we need a more advanced host then OrangeCoat could host.  Though, if we can continue to use GitHub pages then that's one less thing to manage.

**Comment by allella** [comment]
Jake Murphy has offered to create a new site.

**Comment by allella** [comment]
More on GitHub pages
https://help.github.com/articles/creating-pages-with-the-automatic-generator/

**Comment by invisionjeremy** [comment]
We've moved on, and created a basic page. Closing this issue.
